apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: vriddhi
  source:
    path: deployment/prod
    repoURL: https://github.com/anandrahul23/vriddhi-continuous-deployment.git
    targetRevision: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

