apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service-rollout
spec:
  replicas: 4
  strategy:
    blueGreen: null
    canary:
      canaryService: user-service-preview
      stableService: user-service
      trafficRouting:
        nginx:
          stableIngress: user-service-ingress
      steps:
      - setCanaryScale:
          replicas: 2
      - setWeight: 25
      - pause:
          duration: 10s
      - setWeight: 25
      - pause:
          duration: 10s
      - setWeight: 75
      - pause:
          duration: 10s
      - setWeight: 100