apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
    tier: backend
  name: user-service
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8085
  selector:
    app: user-service
  type: ClusterIP
