apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: vriddhi
  source:
    path: userService/deployment/staging
    repoURL: https://github.com/anandrahul23/vriddhi-continuous-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

