# filepath: /Users/rahulanand/Desktop/projects/devops-vriddhi/userService/deployment/staging/replicas-patch.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service-rollout
spec:
  replicas: 2